### ISSUE TITLE
Tab followed by spaces is not updated

### ISSUE THREAD

**Issue by benjaminprojas** [z2oh/gulp-tabify#1]
When running `tabify()` on a line where it starts with a tab, but is then followed by spaces, nothing is changed.  It would be nice if the spaces in a line such as that would also update to tabs:

![image](https://cloud.githubusercontent.com/assets/962530/21553246/54bfd9f4-cdd5-11e6-8bf0-4096a3dd9163.png)

This would only happen if the preceding characters are tabs from the start of the line.  Also, any mix of spaces + tabs + spaces + tabs... until the first non-whitespace character.

I hope this makes sense!

**Comment by z2oh** [comment]
Thanks for catching this; I didn't account for mixed whitespace indentation. I should have a fix out later today.

**Comment by benjaminprojas** [comment]
awesome! look forward to testing.

**Comment by z2oh** [comment]
Just pushed a fix for this. Let me know if it is not the expected behavior and I will reopen this issue. Thanks for pointing this out!

**Comment by benjaminprojas** [comment]
Awesome! I'm not seeing an update in npm. Should I test manually?

**Comment by z2oh** [comment]
Sorry, forgot to re-publish to npm! The latest version should be up on npm now, version 0.0.2.
